name: Build :re.OS ISO

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup EndeavourOS Mirrors & Dependencies
        run: |
          # ۱. آپدیت مخازن و نصب ابزارهای پایه و بیلد
          pacman -Syu --noconfirm
          pacman -S --noconfirm git wget squashfs-tools archiso dosfstools libisoburn lynx cpio dracut sudo

          # ۲. ساخت لیست میرورهای اختصاصی
          mkdir -p /etc/pacman.d
          cat << 'EOF' > /etc/pacman.d/endeavouros-mirrorlist
          Server = https://mirror.alwyzon.net/endeavouros/repo/$repo/$arch
          Server = https://de.mirror.endeavouros.com/repo/$repo/$arch
          Server = https://mirror.linux.net.nu/endeavouros/repo/$repo/$arch
          Server = https://mirror.moson.org/endeavouros/repo/$repo/$arch
          EOF

          # ۳. معرفی مخزن به pacman
          echo -e "\n[endeavouros]\nSigLevel = PackageOptional\nInclude = /etc/pacman.d/endeavouros-mirrorlist" >> /etc/pacman.conf
          pacman -Sy --noconfirm

          # ۴. ساخت یک کاربر غیر روت به نام 'builder' برای دور زدن محدودیت makepkg
          useradd -m builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          
          # ۵. تغییر مالکیت پوشه پروژه به کاربر جدید
          chown -R builder:builder ./

      - name: Prepare ISO Structure (As Non-Root)
        run: |
          chmod +x prepare.sh
          # اجرای اسکریپت آماده‌سازی با کاربر غیر روت
          su builder -c "./prepare.sh"

      - name: Run Build (mkarchiso As Root)
        run: |
          # ابزار mkarchiso برخلاف makepkg حتماً باید با دسترسی روت اجرا شود
          ./mkarchiso -v "."

      - name: Upload ISO Artifact
        uses: actions/upload-artifact@v4
        with:
          name: re-OS-Live-ISO
          path: out/*.iso
          if-no-files-found: error
          retention-days: 5
