name: Build :re.OS ISO

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged # دسترسی لازم برای ساخت فایل‌سیستم ایزو (loop devices)
    
    steps:
      - name: Install Core Dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm git archiso cpio dracut

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Build Script
        run: |
          # دادن دسترسی اجرایی به اسکریپت بیلد
          chmod +x build.sh
          # اجرای اسکریپت با حالت Verbose برای دیدن جزئیات لایو
          ./build.sh -v

      - name: Upload ISO Artifact
        uses: actions/upload-artifact@v4
        with:
          name: re-OS-Live-ISO
          path: out/*.iso
          if-no-files-found: error
          retention-days: 5
