name: Build :re.OS ISO

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup EndeavourOS Repository & Dependencies
        run: |
          # ۱. آپدیت کلیدها و سیستم پایه آرچ
          pacman -Syu --noconfirm
          pacman -S --noconfirm git wget squashfs-tools archiso dosfstools libisoburn lynx

          # ۲. اضافه کردن مخزن رسمی EndeavourOS به pacman (حیاتی برای دانلود calamares و پکیج‌های خاص)
          echo -e "\n[endeavouros]\nSigLevel = PackageOptional\nServer = https://mirror.linux.net.nu/endeavouros/repo/\$repo/\$arch" >> /etc/pacman.conf
          
          # ۳. آپدیت مجدد برای شناسایی مخزن جدید
          pacman -Sy --noconfirm

      - name: Prepare ISO Structure
        run: |
          # اجرای اسکریپت آماده‌سازی محیط طبق README
          chmod +x prepare.sh
          ./prepare.sh

      - name: Run Build (mkarchiso)
        run: |
          # اجرای دستور رسمی بیلد طبق README
          # نقطه "." یعنی از پوشه فعلی به عنوان سورس استفاده کن
          sudo ./mkarchiso -v "."

      - name: Upload ISO Artifact
        uses: actions/upload-artifact@v4
        with:
          name: re-OS-Live-ISO
          path: out/*.iso
          if-no-files-found: error
          retention-days: 5
